[2023-08-08T09:57:02.631+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: local_gcd_gbq.download_file manual__2023-08-08T09:57:00.719489+00:00 [queued]>
[2023-08-08T09:57:02.640+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: local_gcd_gbq.download_file manual__2023-08-08T09:57:00.719489+00:00 [queued]>
[2023-08-08T09:57:02.640+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-08T09:57:02.653+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToLocalFilesystemOperator): download_file> on 2023-08-08 09:57:00.719489+00:00
[2023-08-08T09:57:02.658+0000] {standard_task_runner.py:57} INFO - Started process 401 to run task
[2023-08-08T09:57:02.661+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'local_gcd_gbq', 'download_file', 'manual__2023-08-08T09:57:00.719489+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/example_gcs_upload_download.py', '--cfg-path', '/tmp/tmpk5dq4lw5']
[2023-08-08T09:57:02.663+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask download_file
[2023-08-08T09:57:02.696+0000] {task_command.py:410} INFO - Running <TaskInstance: local_gcd_gbq.download_file manual__2023-08-08T09:57:00.719489+00:00 [running]> on host eb6c146e2e2c
[2023-08-08T09:57:02.752+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='local_gcd_gbq' AIRFLOW_CTX_TASK_ID='download_file' AIRFLOW_CTX_EXECUTION_DATE='2023-08-08T09:57:00.719489+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-08T09:57:00.719489+00:00'
[2023-08-08T09:57:02.754+0000] {gcs_to_local.py:111} INFO - Executing download: dhuyvp, mock_users.csv, ./opt/***/
[2023-08-08T09:57:02.760+0000] {base.py:73} INFO - Using connection ID 'admin' for task execution.
[2023-08-08T09:57:02.806+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_local.py", line 125, in execute
    hook.download(bucket_name=self.bucket, object_name=self.object_name, filename=self.filename)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 340, in download
    blob.download_to_filename(filename, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1255, in download_to_filename
    with open(filename, "wb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: './opt/airflow/'
[2023-08-08T09:57:02.813+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=local_gcd_gbq, task_id=download_file, execution_date=20230808T095700, start_date=20230808T095702, end_date=20230808T095702
[2023-08-08T09:57:02.820+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 13 for task download_file ([Errno 2] No such file or directory: './opt/airflow/'; 401)
[2023-08-08T09:57:02.832+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-08T09:57:02.845+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
