[2023-08-08T09:43:42.245+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: local_gcd_gbq.upload_file manual__2023-08-08T09:43:41.214804+00:00 [queued]>
[2023-08-08T09:43:42.254+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: local_gcd_gbq.upload_file manual__2023-08-08T09:43:41.214804+00:00 [queued]>
[2023-08-08T09:43:42.254+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-08T09:43:42.268+0000] {taskinstance.py:1327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file> on 2023-08-08 09:43:41.214804+00:00
[2023-08-08T09:43:42.274+0000] {standard_task_runner.py:57} INFO - Started process 142 to run task
[2023-08-08T09:43:42.276+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'local_gcd_gbq', 'upload_file', 'manual__2023-08-08T09:43:41.214804+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/example_gcs_upload_download.py', '--cfg-path', '/tmp/tmpgm1me069']
[2023-08-08T09:43:42.278+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask upload_file
[2023-08-08T09:43:42.323+0000] {task_command.py:410} INFO - Running <TaskInstance: local_gcd_gbq.upload_file manual__2023-08-08T09:43:41.214804+00:00 [running]> on host eb6c146e2e2c
[2023-08-08T09:43:42.404+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='local_gcd_gbq' AIRFLOW_CTX_TASK_ID='upload_file' AIRFLOW_CTX_EXECUTION_DATE='2023-08-08T09:43:41.214804+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-08T09:43:41.214804+00:00'
[2023-08-08T09:43:42.430+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 93, in execute
    impersonation_chain=self.impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 165, in __init__
    impersonation_chain=impersonation_chain,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 234, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 463, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2023-08-08T09:43:42.435+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=local_gcd_gbq, task_id=upload_file, execution_date=20230808T094341, start_date=20230808T094342, end_date=20230808T094342
[2023-08-08T09:43:42.446+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 7 for task upload_file (The conn_id `google_cloud_default` isn't defined; 142)
[2023-08-08T09:43:42.492+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-08T09:43:42.507+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
