[2023-08-09T04:09:42.863+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: local_gcd_etl_basic.get_file_path manual__2023-08-09T04:09:41.774489+00:00 [queued]>
[2023-08-09T04:09:42.871+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: local_gcd_etl_basic.get_file_path manual__2023-08-09T04:09:41.774489+00:00 [queued]>
[2023-08-09T04:09:42.871+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-09T04:09:42.887+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): get_file_path> on 2023-08-09 04:09:41.774489+00:00
[2023-08-09T04:09:42.895+0000] {standard_task_runner.py:57} INFO - Started process 691 to run task
[2023-08-09T04:09:42.898+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'local_gcd_etl_basic', 'get_file_path', 'manual__2023-08-09T04:09:41.774489+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/example_gcs_upload_download.py', '--cfg-path', '/tmp/tmp4nc844_g']
[2023-08-09T04:09:42.900+0000] {standard_task_runner.py:85} INFO - Job 53: Subtask get_file_path
[2023-08-09T04:09:42.937+0000] {task_command.py:410} INFO - Running <TaskInstance: local_gcd_etl_basic.get_file_path manual__2023-08-09T04:09:41.774489+00:00 [running]> on host 738c524d2ce7
[2023-08-09T04:09:42.972+0000] {abstractoperator.py:598} ERROR - Exception rendering Jinja template for task 'get_file_path', field 'bash_command'. Template: 'echo {{tasks.download_file.outputs.file_path}}'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'tasks' is undefined
[2023-08-09T04:09:42.973+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 590, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 156, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 540, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/template/templater.py", line 113, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 288, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 283, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'tasks' is undefined
[2023-08-09T04:09:42.981+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=local_gcd_etl_basic, task_id=get_file_path, execution_date=20230809T040941, start_date=20230809T040942, end_date=20230809T040942
[2023-08-09T04:09:42.989+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 53 for task get_file_path ('tasks' is undefined; 691)
[2023-08-09T04:09:43.029+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-09T04:09:43.042+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
